[package]
name = "pretree"
version = "0.1.0"
edition = "2018"
authors = ["wandercn<wander@ffactory.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
